/* Kiem src/kho-dai.js (kho dai Storyboard, 29/09) tren thu muc TAM cua he thong — KHONG dung userData that.
   Chay: npm run test:khodai. Anh gia = doi tuong co getSize/resize/toJPEG (khong can Electron).
   Doi chung an toan: id la / duong dan thoat ra ngoai phai bi tu choi, file ngoai kho phai con nguyen. */
const fs = require('fs'), path = require('path')
const kd = require(path.join(__dirname, '..', '..', 'src', 'kho-dai.js'))
const TAM = path.join(require('os').tmpdir(), 'aio-shotsave-thu-kho-dai-' + process.pid)
fs.rmSync(TAM, { recursive: true, force: true }); fs.mkdirSync(TAM)
const canhBao = path.join(TAM, 'KHONG-DUOC-XOA.txt'); fs.writeFileSync(canhBao, 'x') // file ngoai kho: phai con nguyen
kd.khoiTao(TAM)
const anh = (w, h) => ({ getSize: () => ({ width: w, height: h }), resize: ({ height }) => anh(Math.round(w * height / h), height), toJPEG: () => Buffer.from('jpg' + w + 'x' + h) })
const kq = []; const kiem = (ten, ok) => kq.push((ok ? 'DAT   ' : 'TRUOT ') + ten)
const khung = [1, 2, 3, 4, 5, 6].map((seq) => ({ seq, image: anh(2556, 1484) }))
const id1 = kd.luuDai(khung)
const t0 = Date.now(); while (Date.now() - t0 < 5); // de id khac nhau (ms)
const id2 = kd.luuDai(khung.slice(0, 3))
kiem('luu 2 dai, id dung mau', kd.MAU_ID.test(id1) && kd.MAU_ID.test(id2) && id1 !== id2)
const ds = kd.danhSach()
kiem('danh sach 2 dai, MOI NHAT truoc', ds.length === 2 && ds[0].id === id2)
kiem('khung thu nho ve cao 1080 (2556x1484 -> ' + ds[1].khung[0].w + 'x' + ds[1].khung[0].h + ')', ds[1].khung[0].h === 1080)
const m = kd.boKhung(id1, 3)
kiem('bo khung 3: con 5, GIU SO GOC ' + m.khung.map((k) => k.seq).join(','), m.khung.length === 5 && m.khung.map((k) => k.seq).join(',') === '1,2,4,5,6')
kiem('file khung-3 da xoa, khung-4 con', !fs.existsSync(path.join(TAM, 'storyboard', id1, 'khung-3.jpg')) && fs.existsSync(path.join(TAM, 'storyboard', id1, 'khung-4.jpg')))
kiem('duongKhung khung da bo = null', kd.duongKhung(id1, 3) === null && !!kd.duongKhung(id1, 4))
for (const s of [1, 2, 3]) kd.boKhung(id2, s)
kiem('bo het khung dai 2 -> dai 2 bien mat', kd.danhSach().length === 1 && !fs.existsSync(path.join(TAM, 'storyboard', id2)))
// doi chung an toan: id la / duong dan thoat ra ngoai -> tu choi, khong xoa gi
kiem('xoaDai("..") tu choi', kd.xoaDai('..') === false && kd.xoaDai('../KHONG-DUOC-XOA.txt') === false && kd.xoaDai('') === false)
kiem('duongKhung("..", 1) tu choi', kd.duongKhung('..', 1) === null && kd.duongKhung(id1, '../x') === null)
kiem('file ngoai kho con nguyen', fs.existsSync(canhBao))
kiem('xoaDai dai 1 that', kd.xoaDai(id1) === true && kd.danhSach().length === 0)
console.log(kq.join('\n'))
const dat = kq.every((x) => x.startsWith('DAT'))
console.log(dat ? 'Ket qua: TAT CA DAT (' + kq.length + '/' + kq.length + ')' : 'Ket qua: CO MUC TRUOT')
fs.rmSync(TAM, { recursive: true, force: true })
process.exit(dat ? 0 : 1)
